In [9]:
import caas
from scipy import spatial
import numpy as np

In [10]:
rgb_values = np.asarray([171,195,218])

In [11]:
cd = caas.color_definitions
cd.keys()

dict_keys(['test', 'x11', 'xkcd'])

In [12]:
RGB = cd["test"]["rgbs"]

In [13]:
dist, index = spatial.KDTree(RGB).query(rgb_values,3)
dist
index

array([0, 2, 1])

In [14]:
dist

array([  1.73205081, 116.09048195, 157.56585925])

In [15]:
index

array([0, 2, 1])

In [16]:
p1

NameError: name 'p1' is not defined