In [1]:
import numpy as np

In [2]:
def jet(n):
    r,g,b, = np.zeros(n),np.zeros(n),np.zeros(n)
    for i in range(0,n):
        m=4.0*i/n
        r[i]=255*min(max(min(m-1.5,-m+4.5),0),1)
        g[i]=255*min(max(min(m-0.5,-m+3.5),0),1)
        b[i]=255*min(max(min(m+0.5,-m+2.5),0),1)
    
    return np.uint8(np.c_[r,g,b])
        

In [3]:
jet(3)

array([[  0,   0, 127],
       [  0, 212, 255],
       [255, 212,   0]], dtype=uint8)

In [21]:
img_ind = np.squeeze(np.random.randint(0, high=3, size=(5,5,1)))
print(img_ind)


[[1 1 0 1 1]
 [2 1 0 2 1]
 [2 2 1 0 1]
 [2 2 2 0 1]
 [1 0 1 0 0]]


In [28]:
np.repeat(img_ind[:,:,np.newaxis], repeats=2, axis=2)

array([[[1, 1],
        [1, 1],
        [0, 0],
        [1, 1],
        [1, 1]],

       [[2, 2],
        [1, 1],
        [0, 0],
        [2, 2],
        [1, 1]],

       [[2, 2],
        [2, 2],
        [1, 1],
        [0, 0],
        [1, 1]],

       [[2, 2],
        [2, 2],
        [2, 2],
        [0, 0],
        [1, 1]],

       [[1, 1],
        [0, 0],
        [1, 1],
        [0, 0],
        [0, 0]]])

In [26]:
a = np.ones(shape=(5,5,3));
gray_image = np.average(a, axis=2, weights=[.299, .587, .114]);
print(np.repeat(gray_image[:,:,np.newaxis], repeats=3, axis=2))

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
