In [1]:
import cv2
import numpy as np

In [9]:
imrgb = np.zeros((1,1,3), np.uint8)
imrgb[0,0,0]=100
imrgb[0,0,1]=100
imrgb[0,0,2]=50
print(imrgb)

[[[100 100  50]]]


In [10]:
cv2.cvtColor(imrgb, cv2.COLOR_RGB2LAB)

array([[[105, 120, 156]]], dtype=uint8)

In [11]:
cv2.cvtColor(imrgb, cv2.COLOR_RGB2Lab)

array([[[105, 120, 156]]], dtype=uint8)